export const AccountAdminTypes = {
    PETTY_CASH_APPROVED_LIST:'PETTY_CASH_APPROVED_LIST',
    PETTY_CASH_PENDING_LIST:'PETTY_CASH_PENDING_LIST',
    PARTNER_PAYMENT_LIST:'PARTNER_PAYMENT_LIST',
    PAYMENT_ALL_DELIVERIES:'PAYMENT_ALL_DELIVERY',
    PAYMENT_DELIVERED_DELIVERIES:'PAYMENT_DELIVERED_DELIVERIES',
    PAYMENT_PAID_DELIVERIES:'PAYMENT_PAID_DELIVERIES',
    PAYMENT_RECEIVED_DELIVERIES:'PAYMENT_RECEIVED_DELIVERIES',
    PACKET_EXCHANGED_DELIVERIES:'PACKET_EXCHANGED_DELIVERIES',
    PAYMENT_REQUEST_PARTNER:'PAYMENT_REQUEST_PARTNER',
    ACCOUNT_PENDING_DAILY_STATEMENT:'ACCOUNT_PENDING_DAILY_STATEMENT',
    ACCOUNT_APPROVED_DAILY_STATEMENT:'ACCOUNT_APPROVED_DAILY_STATEMENT',
    ACCOUNT_PAYMENT_PARTNER_STATEMENT_LIST:'ACCOUNT_PAYMENT_PARTNER_STATEMENT_LIST',


}