export const BranchOperationTypes = {

    ASSIGNED_LIST:'ASSIGNED_LIST',
    ASSIGNED_SAME_DAY_LIST:'ASSIGNED_SAME_DAY_LIST',

    All_Hold_list_SAME_DAY:'All_Hold_list_SAME_DAY',
    All_Hold_list:'All_hold_list',

    ALL_RETURNS_LIST:'ALL_RETURNS_LIST',
    ALL_RETURNS_LIST_SAME_DAY:'ALL_RETURNS_LIST_SAME_DAY',

    WAREHOUSE_PRODUCT_LIST_SAME_DAY:'WAREHOUSE_PRODUCT_LIST_SAME_DAY',

    TRANSFER_INS_LIST_SAME_DAY: 'TRANSFER_INS_LIST_SAME_DAY',
    TRANSFER_OUT_LIST_SAME_DAY:'TRANSFER_OUT_LIST_SAME_DAY',
    TRANSFER_OUTS_COMPLETE:'TRANSFER_OUTS_COMPLETE',
    TRANSFER_OUTS_COMPLETE_SAME_DAY:'TRANSFER_OUTS_COMPLETE_SAME_DAY',

    PRINT_SELECTED_DATA:'PRINT_SELECTED_DATA',


    NEW_PICK_SAME_DAY_LIST: 'NEW_PICK_SAME_DAY_LIST',
    SENT_FOR_DELIVERY:'SENT_FOR_DELIVERY',
    SENT_FOR_DELIVERY_SAME_DAY:'SENT_FOR_DELIVERY_SAME_DAY',
    DELIVERED_LIST:'DELIVERED_LIST',
    DELIVERED_LIST_SAME_DAY:'DELIVERED_LIST_SAME_DAY',
    ALL_PICKUP_LIST:'ALL_PICKUP_LIST',

    GET_MESSAGE_DETAIL: 'GET_MESSAGE_DETAIL',

    // image Processing
    IMAGE_PARTNER_REQUEST:'IMAGE_PARTNER_REQUEST',
    IMAGE_PARTNER_PROCEEDED_REQUEST_DETAIL:'IMAGE_PARTNER_PROCEEDED_REQUEST_DETAIL',
    IMAGE_PARTNER_REQUEST_DETAIL:'IMAGE_PARTNER_REQUEST_DETAIL',
    ENTRY_PARTNER_REQUEST_DETAIL:'ENTRY_PARTNER_REQUEST_DETAIL',
    ENTRY_PARTNER_PROCEEDED_REQUEST_DETAIL:'ENTRY_PARTNER_PROCEEDED_REQUEST_DETAIL',


    OPERATION_CURRENT_CUSTOMER_ADDED: 'OPERATION_CURRENT_CUSTOMER_ADDED',

    PROCESS_REQUEST_LIST:'PROCESS_REQUEST_LIST',
    COMPLETE_REQUEST_LIST:'COMPLETE_REQUEST_LIST',

    // print function
    PRINT_DATA_ORDER:'PRINT_DATA_ORDER',

    INCOMING_CANCEL_LIST:'INCOMING_CANCEL_LIST',
    INCOMING_CANCEL_SAME_DAY_LIST:'INCOMING_CANCEL_SAME_DAY_LIST',

    PRODUCT_EXCHANGE_ITEMS:'PRODUCT_EXCHANGE_ITEMS',
    CUSTOMER_REPLACE_ITEMS:'CUSTOMER_REPLACE_ITEMS',

    SINGLE_PICKUP_DETAIL:'SINGLE_PICKUP_DETAIL',

    SINGLE_PICKUP_DETAIL_COORDINATE:'SINGLE_PICKUP_DETAIL_COORDINATE',
    PRINT_ALL_ORDER:'PRINT_ALL_ORDER',

    VENDOR_RETURN_LIST:'VENDOR_RETURN_LIST',

    VENDOR_RETURN_PENDING_STATEMENT:'VENDOR_RETURN_PENDING_STATEMENT',
     VENDOR_RETURN_APPROVED_STATEMENT:'VENDOR_RETURN_APPROVED_STATEMENT',

    SUPER_SEARCH:'SUPER_SEARCH',
















}