// export const AUTHENTICATE_BRANCH = 'AUTHENTICATE_BRANCH';
// export const LOGOUT_BRANCH = 'LOGOUT_BRANCH';

export const BranchTypes = {
    AUTHENTICATE_BRANCH: 'AUTHENTICATE_BRANCH',
    LOGOUT_BRANCH: 'LOGOUT_BRANCH'
}