export const DiscountActionTypes = {
    FETCH_DISCOUNT_SCHEMES: 'FETCH_DISCOUNT_SCHEMES',
    SUBMIT_DISCOUNT_SCHEME: 'SUBMIT_DISCOUNT_SCHEME',
    SELECT_DISCOUNT_SCHEME: 'SUBMIT_DISCOUNT_SCHEME',
    DELETE_DISCOUNT_SCHEME: 'DELETE_DISCOUNT_SCHEME',
    FETCH_REGISTERED_PARTNERS: 'FETCH_REGISTERED_PARTNERS',
    ASSIGN_DISCOUNT_SCHEME: 'ASSIGN_DISCOUNT_SCHEME',
    PROVOKE_DISCOUNT_SCHEME: 'PROVOKE_DISCOUNT_SCHEME',
    CHANGE_DISCOUNT_SCHEME: 'CHANGE_DISCOUNT_SCHEME'
}