export const HrAdminTypes = {
    STAFF_DELIVERY_LIST: 'STAFF_DELIVERY_LIST',
    DELIVERY_PERSON_FOR_COMMISSION:'DELIVERY_PERSON_FOR_COMMISSION',
    STAFF_ROLES:'STAFF_ROLES',
    ENTRY_OPERATOR_LIST:'ENTRY_OPERATOR_LIST',
    MARKETING_LIST:'MARKETING_LIST',
    SET_ID_CARD_LIST: 'SET_ID_CARD_LIST'
}