export const MainBranchesTypes = {
    DELIVERY_PENDING_STATEMENT: 'DELIVERY_PENDING_STATEMENT',
    DELIVERY_APPROVED_STATEMENT:'DELIVERY_APPROVED_STATEMENT',
    DAILY_STATEMENT_EXPENSES_LIST:'DAILY_STATEMENT_EXPENSES_LIST',
    DAILY_STATEMENT_TOTAL_EXPENSES:'DAILY_STATEMENT_TOTAL_EXPENSES',
    DAILY_STATEMENT_PETTY_CASH:'DAILY_STATEMENT_PETTY_CASH',
    DAILY_STATEMENT_TOTAL_PETTY_CASH:'DAILY_STATEMENT_TOTAL_PETTY_CASH',
    DAILY_STATEMENT_TOTAL_CASH_COLLECTED:'DAILY_STATEMENT_TOTAL_CASH_COLLECTED',
    DAILY_STATEMENT:'DAILY_STATEMENT',
    DAILY_STATEMENT_TOTAL_COMMISSION:'DAILY_STATEMENT_TOTAL_COMMISSION',
    DAILY_STATEMENT_TOTAL_DEPOSIT:'DAILY_STATEMENT_TOTAL_DEPOSIT',
    DAILY_STATEMENT_TOTAL_DELIVERY_CHARGE:'DAILY_STATEMENT_TOTAL_DELIVERY_CHARGE',
    DAILY_STATEMENT_RECORD:'DAILY_STATEMENT_RECORD',
    CURRENT_PETTY_CASH:'CURRENT_PETTY_CASH',
    PENDING_DAILY_STATEMENT:'PENDING_DAILY_STATEMENT',
    APPROVED_DAILY_STATEMENT:'APPROVED_DAILY_STATEMENT',


}