export const MainAdminTypes= {
   TRANSFER_RATE_LIST:'TRANSFER_RATE_LIST',
   EDIT_TRANSFER_RATE:'EDIT_TRANSFER_RATE',
   UPDATE_BRANCH_DETAIL:'UPDATE_BRANCH_DETAIL',
   PICKUPS_lIST:'PICKUPS_lIST',
   PICKUP_ASSIGNED_LIST:'PICKUP_ASSIGNED_LIST',
   PICKUP_DELIVERED_LIST:'PICKUP_DELIVERED_LIST',
   PICKUP_ON_THE_WAY_LIST:'PICKUP_ON_THE_WAY_LIST',
   AT_WAREHOUSE_LIST:'AT_WAREHOUSE_LIST',
   BRANCH_LIST_FOR_INPUT:'BRANCH_LIST_FOR_INPUT',
   INTER_TRANSFER_COUNT_LIST:'INTER_TRANSFER_COUNT_LIST',

}
