export const NewPickupTypes = {
    NEW_PICK_LIST: ' NEW_PICK_LIST',
    NEW_PICK_LIST_COUNT: 'NEW_PICK_LIST_COUNT',
    NEW_PICK_SAME_DAY_LIST: 'NEW_PICK_SAME_DAY_LIST',
     NEW_PICK_SAME_DAY_LIST_COUNT: 'NEW_PICK_SAME_DAY_LIST_COUNT',

}