export const PartnerReturnStatementTypes = {
    FETCH_RETURNED_DELIVERIES: 'FETCH_RETURNED_DELIVERIES',
    FETCH_PENDING_RETURN_STATEMENTS: 'FETCH_PENDING_RETURN_STATEMENTS',
    FETCH_APPROVED_RETURN_STATEMENTS: 'FETCH_APPROVED_RETURN_STATEMENTS',
    FETCH_SELECTED_STATEMENT_DELIVERIES: 'FETCH_SELECTED_STATEMENT_DELIVERIES',
    CLEAR_SELECTED_STATEMENT_DELIVERIES: 'CLEAR_SELECTED_STATEMENT_DELIVERIES',
    REMOVE_DETAILS: 'REMOVE_DETAILS'
}