export const partnerTypes = {
    LOAD_PARTNER_LIST: 'LOAD_PARTNER_LIST',
    UPDATE_PARTNER: 'UPDATE_PARTNER',
    REFRESH_PARTNER_LIST: 'REFRESH_PARTNER_LIST',
    AUTHENTICATE_PARTNER: 'AUTHENTICATE_PARTNER',
}