export const PartnerPaymentTypes = {
    FETCH_DELIVERIES: ' FETCH_DELIVERIES',
    FETCH_PICKUPS: ' FETCH_PICKUPS',
    FETCH_RETURNS: ' FETCH_RETURNS',
    FETCH_CALCULATION_DETAILS: 'FETCH_CALCULATION_DETAILS',
    CLEAR_PAYMENT_DETAILS: 'CLEAR_PAYMENT_DETAILS',
}