export const TransferTypes = {
    TRANSFER_INS_LIST: 'TRANSFER_INS_LIST',
    TRANSFER_INS_LIST_SAME_DAY: 'TRANSFER_INS_LIST_SAME_DAY',
    TRANSFER_INS_COUNT:'TRANSFER_INS_COUNT',
    TRANSFER_OUT_LIST:'TRANSFER_OUT_LIST',
    TRANSFER_OUT_LIST_SAME_DAY:'TRANSFER_OUT_LIST_SAME_DAY',
    TRANSFER_OUT_COUNT:'TRASNFER_OUT_COUNT',
    TRANSFER_ALL_BRANCH:'TRANSFER_ALL_BRANCH'

}