export const VendorTypes={
    ALL_DELIVERIES: 'ALL_DELIVERIES',
    ALL_MESSAGE_LIST:'ALL_MESSAGE_LIST',
    GET_MESSAGE_DETAIL:'GET_MESSAGE_LIST',
    SINGLE_PICKUP_DETAIL:'SINGLE_PICKUP_DETAIL',
    PENDING_ORDER_LIST:'PENDING_ORDER_LIST',
    SETTLE_ORDER_LIST:'SETTLE_ORDER_LIST',
    SEARCH_ORDER_LIST:'SEARCH_ORDER_LIST',
    STATEMENTS_AND_INVOICES:'STATEMENTS_AND_INVOICES',
    ALL_CUSTOMER_LIST:'ALL_CUSTOMER_LIST',
    ALL_CUSTOMER_LIST_DISPLAY:'ALL_CUSTOMER_LIST_DISPLAY',
    ALL_HOLD_DELIVERIES:'ALL_HOLD_DELIVERIES',
    ALL_RETURNS_DELIVERIES:'ALL_RETURNS_DELIVERIES',
    NEW_REQUEST_LIST:'NEW_REQUEST_LIST',
    PARTNER_CURRENT_CUSTOMER_ADDED:'PARTNER_CURRENT_CUSTOMER_ADDED',
    Hold_ORDER_LIST:'Hold_ORDER_LIST',
    Hold_ORDER_CONFIRM_LIST:'Hold_ORDER_CONFIRM_LIST',
    RETURN_ORDER_LIST:'RETURN_ORDER_LIST',
    RETURN_ORDER_CONFIRM_LIST:'RETURN_ORDER_CONFIRM_LIST',
    STATEMENTS_AND_INVOICES_HOLDS:'STATEMENTS_AND_INVOICES_HOLDS',
    PRODUCT_EXCHANGE_ITEMS:'PRODUCT_EXCHANGE_ITEMS',
    REQUEST_IMAGE_DETAIL:'REQUEST_IMAGE_DETAIL',
    REQUEST_ENTRY_DETAIL:'REQUEST_ENTRY_DETAIL',
    ALL_PROCESS_PICKUP:'ALL_PROCESS_PICKUP',
    ALL_PICKUP_ORDER:'ALL_PICKUP_ORDER',
    CUSTOMER_REPLACE_ITEMS:'CUSTOMER_REPLACE_ITEMS',
    GET_SINGLE_PICKUP_LOCATION:'GET_SINGLE_PICKUP_LOCATION',
    DELIVERY_PERSON_CURRENT_LOCATION:'DELIVERY_CURRENT_LOCATION',
    PENDING_RETURN_STATEMENT:'PENDING_RETURN_STATEMENT',
    APPROVED_RETURN_STATEMENT:'APPROVED_RETURN_STATEMENT',
    ALL_BANNER_LIST:'ALL_BANNER_LIST',
    ALL_NOTICES_LIST:'ALL_NOTICES_LIST',
    FETCH_PAYMENT_RECEIVED_DELIVERIES: 'FETCH_PAYMENT_RECEIVED_DELIVERIES'





}