export const warehouseTypes = {

    WAREHOUSE_PRODUCT_LIST:'WAREHOUSE_PRODUCT_LIST',
    WAREHOUSE_PRODUCT_LIST_COUNT:'WAREHOUSE_PRODUCT_LIST_COUNT',
    ASSIGN_DELIVERY_PERSON:'ASSIGN_DELIVERY_PERSON',
}